name: Update Hebei TV Link

on:
  schedule:
    - cron: '0 * * * *'  # 每小时整点运行
  workflow_dispatch:     # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # 密钥注入

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # 指定明确版本

      - name: Generate M3U
        run: |
          python generate_hebtv_m3u.py
          ls -al  # 调试：查看文件是否生成

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git pull origin main
          git add hebtv.m3u
          git commit -m "Auto-update $(date +'%Y%m%d-%H%M%S')"
          git push origin main
